convert to modern build system with hatch
Original code used distutils which is dropped from Python 3.12 on.
Though setuptools are kind of the replacement, their use is
discourage.

Use hatch.

**Not working yet.**

* Change license in .constants.json to a  format that hatch
  recognizes; the old "GPL v3" ->
```
ross@barley:/usr/local/src/gnumeric-py$ date; pip3 install -e .
Thu 22 Feb 2024 11:42:11 PM PST
Obtaining file:///usr/local/src/gnumeric-py
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmp7mo_8i9s_in_process.py prepare_metadata_for_build_wheel /tmp/tmprmbm3wtr
         cwd: /usr/local/src/gnumeric-py
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/tmp/tmp7mo_8i9s_in_process.py", line 280, in <module>
        main()
      File "/tmp/tmp7mo_8i9s_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmp7mo_8i9s_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-a_21qvbp/overlay/lib/python3.9/site-packages/hatchling/build.py", line 116, in prepare_metadata_for_build_wheel
        f.write(builder.config.core_metadata_constructor(builder.metadata))
      File "/tmp/pip-build-env-a_21qvbp/overlay/lib/python3.9/site-packages/hatchling/metadata/spec.py", line 109, in construct_metadata_file_2_1
        if metadata.core.license:
      File "/tmp/pip-build-env-a_21qvbp/overlay/lib/python3.9/site-packages/hatchling/metadata/core.py", line 661, in license
        raise ValueError(message) from None
    ValueError: Error parsing field `project.license` - invalid license expression: GPL v3
    ----------------------------------------
WARNING: Discarding file:///usr/local/src/gnumeric-py. Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp7mo_8i9s_in_process.py prepare_metadata_for_build_wheel /tmp/tmprmbm3wtr Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp7mo_8i9s_in_process.py prepare_metadata_for_build_wheel /tmp/tmprmbm3wtr Check the logs for full command output.
```

* create hatch_build.py to get dynamic properties from
  .constants.json.

* Fill in pyproject.toml.

Current build results:
```
ross@barley:/usr/local/src/gnumeric-py$ date; pip3 install -e .
Fri 23 Feb 2024 12:22:29 AM PST
Obtaining file:///usr/local/src/gnumeric-py
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from Gnumeric-py==0.0.1) (4.6.3)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from Gnumeric-py==0.0.1) (2.8.1)
Requirement already satisfied: lark-parser in /usr/lib/python3/dist-packages (from Gnumeric-py==0.0.1) (0.10.0)
Installing collected packages: Gnumeric-py
  Attempting uninstall: Gnumeric-py
    Found existing installation: Gnumeric-py 0.0.1
    Uninstalling Gnumeric-py-0.0.1:
      Successfully uninstalled Gnumeric-py-0.0.1
  Running setup.py develop for Gnumeric-py
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/local/src/gnumeric-py/setup.py'"'"'; __file__='"'"'/usr/local/src/gnumeric-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /usr/local/src/gnumeric-py/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
  Rolling back uninstall of Gnumeric-py
  Moving to /home/ross/.local/lib/python3.9/site-packages/Gnumeric-py.egg-link
   from /tmp/pip-uninstall-o1kom1su/Gnumeric-py.egg-link
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/local/src/gnumeric-py/setup.py'"'"'; __file__='"'"'/usr/local/src/gnumeric-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

Why is it using setuptools at all?  Maybe uninstalling the old module?
But I don't see it in `pip3 list` or pip3 list --user`.